name: Bug report
description: Standard bug report template
assignees:
  - woodonggyu
labels: ["type: bug"]
body:
  - type: input
    id: contact
    attributes:
      label: Contact
      placeholder: input your email
    validations:
      required: false